%YAML:1.0

# Project
project_name: "lvi_sam" 

#common parameters
imu_topic: "/imu/data"                              #注意用的哪个IMU
image_topic: "/images/raw5"
point_cloud_topic: "lvi_sam/lidar/deskew/cloud_deskewed"
output_path: "/home/yabao/output/NCLT/2012-02-04/camera"    #yabao

# Lidar Params
use_lidar: 1                     # whether use depth info from lidar or not
lidar_skip: 3                    # skip this amount of scans
align_camera_lidar_estimation: 1 # align camera and lidar estimation for visualization

# lidar to camera extrinsic
lidar_to_cam_tx: 0.273033
lidar_to_cam_ty: 0.00682854
lidar_to_cam_tz: -0.0734614
lidar_to_cam_rx: 1.5795181
lidar_to_cam_ry: 0.0253506
lidar_to_cam_rz: 1.5718613

# imu to lidar extrinsic
imu_to_lidar_tx: 0.176645
imu_to_lidar_ty: -0.106335
imu_to_lidar_tz: 0.249035
imu_to_lidar_rx: -0.0027242
imu_to_lidar_ry: 0.0141193
imu_to_lidar_rz: 1.5830672

# camera model
model_type: PINHOLE
camera_name: camera

image_width: 1232
image_height: 1616
distortion_parameters:
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
projection_parameters:
  fx: 399.433184
  fy: 399.433184
  cx: 826.361952
  cy: 621.668624


#imu parameters       The more accurate parameters you provide, the worse performance
acc_n: 0.1         # accelerometer measurement noise standard deviation.
gyr_n: 0.01         # gyroscope measurement noise standard deviation.
acc_w: 0.001        # accelerometer bias random work noise standard deviation.
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.
g_norm: 9.805       # gravity magnitude
imu_hz: 150         # frequency of imu

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.00541245, 0.0130744, 0.9999,  
         -0.00176622, -0.999913, 0.0130651, 
          0.999984, -0.00169533, 0.00543507]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.186843, 0.18427, -0.519618]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 20                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04   # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0  # keyframe selection threshold (pixel)

#unsynchronization parameters
estimate_td: 0           # online estimate time offset between camera and imu
td: 0                   # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0       # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0    # unit: s. rolling shutter read out time per frame (from data sheet). 

#loop closure parameters
loop_closure: 1                    # start loop closure
skip_time: 0.0
skip_dist: 0.0
debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 
match_image_scale: 0.5
vocabulary_file: "/config/brief_k10L6.bin"
brief_pattern_file: "/config/brief_pattern.yml"
pose_graph_save_path: "/home/yabao/output/NCLT/2012-02-04/camera/pose_graph/" 
